config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: %i[show update]

  resources :rooms do
    resources :messages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  broadcasts_to :room
  after_create_commit -> {
    broadcast_append_to(
      :messages,
      target: 'toast_container',
      partial: 'messages/message_toast'
    )
  }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def require_login
    authenticate_user!
  end
end

app/controllers/devise_turbo_controller.rb
class DeviseTurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[new create]
  before_action :require_login

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params.merge(user: current_user))

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :require_login

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.select('rooms.*, COUNT(messages.id) as messages_count').left_joins(:messages).group(:id)
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    respond_to do |format|
      format.html { super }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('notifications', partial: 'notifications')
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notification_classes(type)
    case type
    when 'alert'
      'alert alert-danger'
    when 'notice'
      'alert alert-info'
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/application/_header.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>">Test chat</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= rooms_path %>">Rooms</a>
          </li>
        </ul>
        <form class="d-flex">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
        </form>
      </div>
    </div>
  </nav>
</header>

app/views/application/_notifications.html.erb
<div id="notifications">
  <% flash.each do |type, msg| %>
    <div class="<%= notification_classes(type) %>">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>KaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render "header" %>

    <main class="flex-shrink-0">
      <div class="container">
        <%= render "notifications" %>

        <%= yield %>
      </div>
    </main>

    <div id="toast_container" class="toast-container position-fixed bottom-0 end-0 p-3"></div>
  </body>
</html>

app/views/messages/_message.html.erb
<p id="<%= dom_id message %>">
  (<%= message.created_at.to_fs(:short) %>)
  <% if message.user.present? %><strong><%= message.user.email %></strong><% end %>:
  <%= message.content %>
</p>

app/views/messages/_message_toast.html.erb
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <!-- <img src="..." class="rounded me-2" alt="..."> -->
    <strong class="me-auto"><%= message.room.name %></strong>
    <!-- <small class="text-muted">just now</small> -->
    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body">
    (<%= message.created_at.to_fs(:short) %>)
    <% if message.user.present? %><strong><%= message.user.email %></strong><% end %>:
    <%= message.content %>
  </div>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages", @message %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= turbo_frame_tag "new_message", target: "_top" do %>
  <%= form_with(model: [ @message.room, @message ],
                data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form| %>
    <div class="field">
      <%= form.text_field :content %>
      <%= form.submit "Send" %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', @message.room %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <li class="list-group-item d-flex justify-content-between">
    <strong><%= link_to room.name, room %></strong>
    <span class="badge bg-primary rounded-pill"><%= room.messages_count %></span>
  </li>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render "form", room: @room %>
<% end %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<ul id="rooms" class="list-group">
  <% @rooms.each do |room| %>
    <%= render room %>
  <% end %>
</ul>

<br/>

<%= link_to "New room", new_room_path, class: 'btn btn-primary' %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<%= turbo_stream_from(:messages) %>
<div data-controller="messages_stream"></div>

<%= turbo_frame_tag "room" do %>
  <h1>
    <%= @room.name %>
  </h1>
<% end %>

<div id="messages">
  <%= render @room.messages %>
</div>

<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>